/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NamiotImprezowyWynajemRouteImport } from './routes/namiot-imprezowy-wynajem'
import { Route as MaszynaDoWatyCukrowejWynajemRouteImport } from './routes/maszyna-do-waty-cukrowej-wynajem'
import { Route as MaszynaDoPopcornuWynajemRouteImport } from './routes/maszyna-do-popcornu-wynajem'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DmuchaneZjezdzalnieWynajemRouteImport } from './routes/dmuchane-zjezdzalnie-wynajem'
import { Route as DmuchanePlaceZabawWynajemRouteImport } from './routes/dmuchane-place-zabaw-wynajem'
import { Route as DmuchanceNaUrodzinyRouteImport } from './routes/dmuchance-na-urodziny'
import { Route as DmuchanceNaKomunieRouteImport } from './routes/dmuchance-na-komunie'
import { Route as DmuchanceNaFestynyRouteImport } from './routes/dmuchance-na-festyny'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ReservationPublicTokenRouteImport } from './routes/reservation.$publicToken'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAvailabilityRouteImport } from './routes/admin.availability'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminRequestsIndexRouteImport } from './routes/admin.requests.index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin.bookings.index'
import { Route as AdminAuditIndexRouteImport } from './routes/admin.audit.index'
import { Route as AdminRequestsIdRouteImport } from './routes/admin.requests.$id'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as AdminBookingsIdRouteImport } from './routes/admin.bookings.$id'
import { Route as AdminAuditIdRouteImport } from './routes/admin.audit.$id'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NamiotImprezowyWynajemRoute = NamiotImprezowyWynajemRouteImport.update({
  id: '/namiot-imprezowy-wynajem',
  path: '/namiot-imprezowy-wynajem',
  getParentRoute: () => rootRouteImport,
} as any)
const MaszynaDoWatyCukrowejWynajemRoute =
  MaszynaDoWatyCukrowejWynajemRouteImport.update({
    id: '/maszyna-do-waty-cukrowej-wynajem',
    path: '/maszyna-do-waty-cukrowej-wynajem',
    getParentRoute: () => rootRouteImport,
  } as any)
const MaszynaDoPopcornuWynajemRoute =
  MaszynaDoPopcornuWynajemRouteImport.update({
    id: '/maszyna-do-popcornu-wynajem',
    path: '/maszyna-do-popcornu-wynajem',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DmuchaneZjezdzalnieWynajemRoute =
  DmuchaneZjezdzalnieWynajemRouteImport.update({
    id: '/dmuchane-zjezdzalnie-wynajem',
    path: '/dmuchane-zjezdzalnie-wynajem',
    getParentRoute: () => rootRouteImport,
  } as any)
const DmuchanePlaceZabawWynajemRoute =
  DmuchanePlaceZabawWynajemRouteImport.update({
    id: '/dmuchane-place-zabaw-wynajem',
    path: '/dmuchane-place-zabaw-wynajem',
    getParentRoute: () => rootRouteImport,
  } as any)
const DmuchanceNaUrodzinyRoute = DmuchanceNaUrodzinyRouteImport.update({
  id: '/dmuchance-na-urodziny',
  path: '/dmuchance-na-urodziny',
  getParentRoute: () => rootRouteImport,
} as any)
const DmuchanceNaKomunieRoute = DmuchanceNaKomunieRouteImport.update({
  id: '/dmuchance-na-komunie',
  path: '/dmuchance-na-komunie',
  getParentRoute: () => rootRouteImport,
} as any)
const DmuchanceNaFestynyRoute = DmuchanceNaFestynyRouteImport.update({
  id: '/dmuchance-na-festyny',
  path: '/dmuchance-na-festyny',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ReservationPublicTokenRoute = ReservationPublicTokenRouteImport.update({
  id: '/reservation/$publicToken',
  path: '/reservation/$publicToken',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvailabilityRoute = AdminAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsIndexRoute = AdminRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRequestsRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBookingsRoute,
} as any)
const AdminAuditIndexRoute = AdminAuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuditRoute,
} as any)
const AdminRequestsIdRoute = AdminRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRequestsRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminBookingsIdRoute = AdminBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBookingsRoute,
} as any)
const AdminAuditIdRoute = AdminAuditIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAuditRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/dmuchance-na-festyny': typeof DmuchanceNaFestynyRoute
  '/dmuchance-na-komunie': typeof DmuchanceNaKomunieRoute
  '/dmuchance-na-urodziny': typeof DmuchanceNaUrodzinyRoute
  '/dmuchane-place-zabaw-wynajem': typeof DmuchanePlaceZabawWynajemRoute
  '/dmuchane-zjezdzalnie-wynajem': typeof DmuchaneZjezdzalnieWynajemRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/maszyna-do-popcornu-wynajem': typeof MaszynaDoPopcornuWynajemRoute
  '/maszyna-do-waty-cukrowej-wynajem': typeof MaszynaDoWatyCukrowejWynajemRoute
  '/namiot-imprezowy-wynajem': typeof NamiotImprezowyWynajemRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRouteWithChildren
  '/terms': typeof TermsRoute
  '/todos': typeof TodosRoute
  '/admin/audit': typeof AdminAuditRouteWithChildren
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/reservation/$publicToken': typeof ReservationPublicTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/audit/$id': typeof AdminAuditIdRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/admin/audit/': typeof AdminAuditIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/dmuchance-na-festyny': typeof DmuchanceNaFestynyRoute
  '/dmuchance-na-komunie': typeof DmuchanceNaKomunieRoute
  '/dmuchance-na-urodziny': typeof DmuchanceNaUrodzinyRoute
  '/dmuchane-place-zabaw-wynajem': typeof DmuchanePlaceZabawWynajemRoute
  '/dmuchane-zjezdzalnie-wynajem': typeof DmuchaneZjezdzalnieWynajemRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/maszyna-do-popcornu-wynajem': typeof MaszynaDoPopcornuWynajemRoute
  '/maszyna-do-waty-cukrowej-wynajem': typeof MaszynaDoWatyCukrowejWynajemRoute
  '/namiot-imprezowy-wynajem': typeof NamiotImprezowyWynajemRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/todos': typeof TodosRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/reservation/$publicToken': typeof ReservationPublicTokenRoute
  '/admin': typeof AdminIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/audit/$id': typeof AdminAuditIdRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/admin/audit': typeof AdminAuditIndexRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/dmuchance-na-festyny': typeof DmuchanceNaFestynyRoute
  '/dmuchance-na-komunie': typeof DmuchanceNaKomunieRoute
  '/dmuchance-na-urodziny': typeof DmuchanceNaUrodzinyRoute
  '/dmuchane-place-zabaw-wynajem': typeof DmuchanePlaceZabawWynajemRoute
  '/dmuchane-zjezdzalnie-wynajem': typeof DmuchaneZjezdzalnieWynajemRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/maszyna-do-popcornu-wynajem': typeof MaszynaDoPopcornuWynajemRoute
  '/maszyna-do-waty-cukrowej-wynajem': typeof MaszynaDoWatyCukrowejWynajemRoute
  '/namiot-imprezowy-wynajem': typeof NamiotImprezowyWynajemRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRouteWithChildren
  '/terms': typeof TermsRoute
  '/todos': typeof TodosRoute
  '/admin/audit': typeof AdminAuditRouteWithChildren
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/reservation/$publicToken': typeof ReservationPublicTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/audit/$id': typeof AdminAuditIdRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/admin/audit/': typeof AdminAuditIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/dmuchance-na-festyny'
    | '/dmuchance-na-komunie'
    | '/dmuchance-na-urodziny'
    | '/dmuchane-place-zabaw-wynajem'
    | '/dmuchane-zjezdzalnie-wynajem'
    | '/faq'
    | '/login'
    | '/maszyna-do-popcornu-wynajem'
    | '/maszyna-do-waty-cukrowej-wynajem'
    | '/namiot-imprezowy-wynajem'
    | '/privacy-policy'
    | '/products'
    | '/terms'
    | '/todos'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/requests'
    | '/admin/settings'
    | '/categories/$slug'
    | '/products/$slug'
    | '/reservation/$publicToken'
    | '/admin/'
    | '/products/'
    | '/admin/audit/$id'
    | '/admin/bookings/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/requests/$id'
    | '/admin/audit/'
    | '/admin/bookings/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/dmuchance-na-festyny'
    | '/dmuchance-na-komunie'
    | '/dmuchance-na-urodziny'
    | '/dmuchane-place-zabaw-wynajem'
    | '/dmuchane-zjezdzalnie-wynajem'
    | '/faq'
    | '/login'
    | '/maszyna-do-popcornu-wynajem'
    | '/maszyna-do-waty-cukrowej-wynajem'
    | '/namiot-imprezowy-wynajem'
    | '/privacy-policy'
    | '/terms'
    | '/todos'
    | '/admin/availability'
    | '/admin/calendar'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/settings'
    | '/categories/$slug'
    | '/products/$slug'
    | '/reservation/$publicToken'
    | '/admin'
    | '/products'
    | '/admin/audit/$id'
    | '/admin/bookings/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/requests/$id'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/requests'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/dmuchance-na-festyny'
    | '/dmuchance-na-komunie'
    | '/dmuchance-na-urodziny'
    | '/dmuchane-place-zabaw-wynajem'
    | '/dmuchane-zjezdzalnie-wynajem'
    | '/faq'
    | '/login'
    | '/maszyna-do-popcornu-wynajem'
    | '/maszyna-do-waty-cukrowej-wynajem'
    | '/namiot-imprezowy-wynajem'
    | '/privacy-policy'
    | '/products'
    | '/terms'
    | '/todos'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/requests'
    | '/admin/settings'
    | '/categories/$slug'
    | '/products/$slug'
    | '/reservation/$publicToken'
    | '/admin/'
    | '/products/'
    | '/admin/audit/$id'
    | '/admin/bookings/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/requests/$id'
    | '/admin/audit/'
    | '/admin/bookings/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  DmuchanceNaFestynyRoute: typeof DmuchanceNaFestynyRoute
  DmuchanceNaKomunieRoute: typeof DmuchanceNaKomunieRoute
  DmuchanceNaUrodzinyRoute: typeof DmuchanceNaUrodzinyRoute
  DmuchanePlaceZabawWynajemRoute: typeof DmuchanePlaceZabawWynajemRoute
  DmuchaneZjezdzalnieWynajemRoute: typeof DmuchaneZjezdzalnieWynajemRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  MaszynaDoPopcornuWynajemRoute: typeof MaszynaDoPopcornuWynajemRoute
  MaszynaDoWatyCukrowejWynajemRoute: typeof MaszynaDoWatyCukrowejWynajemRoute
  NamiotImprezowyWynajemRoute: typeof NamiotImprezowyWynajemRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  TermsRoute: typeof TermsRoute
  TodosRoute: typeof TodosRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ReservationPublicTokenRoute: typeof ReservationPublicTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namiot-imprezowy-wynajem': {
      id: '/namiot-imprezowy-wynajem'
      path: '/namiot-imprezowy-wynajem'
      fullPath: '/namiot-imprezowy-wynajem'
      preLoaderRoute: typeof NamiotImprezowyWynajemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maszyna-do-waty-cukrowej-wynajem': {
      id: '/maszyna-do-waty-cukrowej-wynajem'
      path: '/maszyna-do-waty-cukrowej-wynajem'
      fullPath: '/maszyna-do-waty-cukrowej-wynajem'
      preLoaderRoute: typeof MaszynaDoWatyCukrowejWynajemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maszyna-do-popcornu-wynajem': {
      id: '/maszyna-do-popcornu-wynajem'
      path: '/maszyna-do-popcornu-wynajem'
      fullPath: '/maszyna-do-popcornu-wynajem'
      preLoaderRoute: typeof MaszynaDoPopcornuWynajemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmuchane-zjezdzalnie-wynajem': {
      id: '/dmuchane-zjezdzalnie-wynajem'
      path: '/dmuchane-zjezdzalnie-wynajem'
      fullPath: '/dmuchane-zjezdzalnie-wynajem'
      preLoaderRoute: typeof DmuchaneZjezdzalnieWynajemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmuchane-place-zabaw-wynajem': {
      id: '/dmuchane-place-zabaw-wynajem'
      path: '/dmuchane-place-zabaw-wynajem'
      fullPath: '/dmuchane-place-zabaw-wynajem'
      preLoaderRoute: typeof DmuchanePlaceZabawWynajemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmuchance-na-urodziny': {
      id: '/dmuchance-na-urodziny'
      path: '/dmuchance-na-urodziny'
      fullPath: '/dmuchance-na-urodziny'
      preLoaderRoute: typeof DmuchanceNaUrodzinyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmuchance-na-komunie': {
      id: '/dmuchance-na-komunie'
      path: '/dmuchance-na-komunie'
      fullPath: '/dmuchance-na-komunie'
      preLoaderRoute: typeof DmuchanceNaKomunieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmuchance-na-festyny': {
      id: '/dmuchance-na-festyny'
      path: '/dmuchance-na-festyny'
      fullPath: '/dmuchance-na-festyny'
      preLoaderRoute: typeof DmuchanceNaFestynyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/reservation/$publicToken': {
      id: '/reservation/$publicToken'
      path: '/reservation/$publicToken'
      fullPath: '/reservation/$publicToken'
      preLoaderRoute: typeof ReservationPublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/availability': {
      id: '/admin/availability'
      path: '/availability'
      fullPath: '/admin/availability'
      preLoaderRoute: typeof AdminAvailabilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests/': {
      id: '/admin/requests/'
      path: '/'
      fullPath: '/admin/requests/'
      preLoaderRoute: typeof AdminRequestsIndexRouteImport
      parentRoute: typeof AdminRequestsRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminBookingsRoute
    }
    '/admin/audit/': {
      id: '/admin/audit/'
      path: '/'
      fullPath: '/admin/audit/'
      preLoaderRoute: typeof AdminAuditIndexRouteImport
      parentRoute: typeof AdminAuditRoute
    }
    '/admin/requests/$id': {
      id: '/admin/requests/$id'
      path: '/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AdminRequestsIdRouteImport
      parentRoute: typeof AdminRequestsRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/bookings/$id': {
      id: '/admin/bookings/$id'
      path: '/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AdminBookingsIdRouteImport
      parentRoute: typeof AdminBookingsRoute
    }
    '/admin/audit/$id': {
      id: '/admin/audit/$id'
      path: '/$id'
      fullPath: '/admin/audit/$id'
      preLoaderRoute: typeof AdminAuditIdRouteImport
      parentRoute: typeof AdminAuditRoute
    }
  }
}

interface AdminAuditRouteChildren {
  AdminAuditIdRoute: typeof AdminAuditIdRoute
  AdminAuditIndexRoute: typeof AdminAuditIndexRoute
}

const AdminAuditRouteChildren: AdminAuditRouteChildren = {
  AdminAuditIdRoute: AdminAuditIdRoute,
  AdminAuditIndexRoute: AdminAuditIndexRoute,
}

const AdminAuditRouteWithChildren = AdminAuditRoute._addFileChildren(
  AdminAuditRouteChildren,
)

interface AdminBookingsRouteChildren {
  AdminBookingsIdRoute: typeof AdminBookingsIdRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
}

const AdminBookingsRouteChildren: AdminBookingsRouteChildren = {
  AdminBookingsIdRoute: AdminBookingsIdRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
}

const AdminBookingsRouteWithChildren = AdminBookingsRoute._addFileChildren(
  AdminBookingsRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRequestsRouteChildren {
  AdminRequestsIdRoute: typeof AdminRequestsIdRoute
  AdminRequestsIndexRoute: typeof AdminRequestsIndexRoute
}

const AdminRequestsRouteChildren: AdminRequestsRouteChildren = {
  AdminRequestsIdRoute: AdminRequestsIdRoute,
  AdminRequestsIndexRoute: AdminRequestsIndexRoute,
}

const AdminRequestsRouteWithChildren = AdminRequestsRoute._addFileChildren(
  AdminRequestsRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRouteWithChildren
  AdminAvailabilityRoute: typeof AdminAvailabilityRoute
  AdminBookingsRoute: typeof AdminBookingsRouteWithChildren
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminRequestsRoute: typeof AdminRequestsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRouteWithChildren,
  AdminAvailabilityRoute: AdminAvailabilityRoute,
  AdminBookingsRoute: AdminBookingsRouteWithChildren,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminRequestsRoute: AdminRequestsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  DmuchanceNaFestynyRoute: DmuchanceNaFestynyRoute,
  DmuchanceNaKomunieRoute: DmuchanceNaKomunieRoute,
  DmuchanceNaUrodzinyRoute: DmuchanceNaUrodzinyRoute,
  DmuchanePlaceZabawWynajemRoute: DmuchanePlaceZabawWynajemRoute,
  DmuchaneZjezdzalnieWynajemRoute: DmuchaneZjezdzalnieWynajemRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  MaszynaDoPopcornuWynajemRoute: MaszynaDoPopcornuWynajemRoute,
  MaszynaDoWatyCukrowejWynajemRoute: MaszynaDoWatyCukrowejWynajemRoute,
  NamiotImprezowyWynajemRoute: NamiotImprezowyWynajemRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  TermsRoute: TermsRoute,
  TodosRoute: TodosRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ReservationPublicTokenRoute: ReservationPublicTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
