/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WynajemRouteImport } from './routes/wynajem'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as ProduktyRouteImport } from './routes/produkty'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as NamiotImprezowyWynajemRouteImport } from './routes/namiot-imprezowy-wynajem'
import { Route as MaszynaDoWatyCukrowejWynajemRouteImport } from './routes/maszyna-do-waty-cukrowej-wynajem'
import { Route as MaszynaDoPopcornuWynajemRouteImport } from './routes/maszyna-do-popcornu-wynajem'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DmuchaneZjezdzalnieWynajemRouteImport } from './routes/dmuchane-zjezdzalnie-wynajem'
import { Route as DmuchanePlaceZabawWynajemRouteImport } from './routes/dmuchane-place-zabaw-wynajem'
import { Route as DmuchanceNaUrodzinyRouteImport } from './routes/dmuchance-na-urodziny'
import { Route as DmuchanceNaKomunieRouteImport } from './routes/dmuchance-na-komunie'
import { Route as DmuchanceNaFestynyRouteImport } from './routes/dmuchance-na-festyny'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RezerwacjaPublicTokenRouteImport } from './routes/rezerwacja.$publicToken'
import { Route as ProduktySlugRouteImport } from './routes/produkty.$slug'
import { Route as KategorieSlugRouteImport } from './routes/kategorie.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAvailabilityRouteImport } from './routes/admin.availability'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminRequestsIdRouteImport } from './routes/admin.requests.$id'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'
import { Route as AdminBookingsIdRouteImport } from './routes/admin.bookings.$id'

const WynajemRoute = WynajemRouteImport.update({
  id: '/wynajem',
  path: '/wynajem',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktyRoute = ProduktyRouteImport.update({
  id: '/produkty',
  path: '/produkty',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const NamiotImprezowyWynajemRoute = NamiotImprezowyWynajemRouteImport.update({
  id: '/namiot-imprezowy-wynajem',
  path: '/namiot-imprezowy-wynajem',
  getParentRoute: () => rootRouteImport,
} as any)
const MaszynaDoWatyCukrowejWynajemRoute =
  MaszynaDoWatyCukrowejWynajemRouteImport.update({
    id: '/maszyna-do-waty-cukrowej-wynajem',
    path: '/maszyna-do-waty-cukrowej-wynajem',
    getParentRoute: () => rootRouteImport,
  } as any)
const MaszynaDoPopcornuWynajemRoute =
  MaszynaDoPopcornuWynajemRouteImport.update({
    id: '/maszyna-do-popcornu-wynajem',
    path: '/maszyna-do-popcornu-wynajem',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DmuchaneZjezdzalnieWynajemRoute =
  DmuchaneZjezdzalnieWynajemRouteImport.update({
    id: '/dmuchane-zjezdzalnie-wynajem',
    path: '/dmuchane-zjezdzalnie-wynajem',
    getParentRoute: () => rootRouteImport,
  } as any)
const DmuchanePlaceZabawWynajemRoute =
  DmuchanePlaceZabawWynajemRouteImport.update({
    id: '/dmuchane-place-zabaw-wynajem',
    path: '/dmuchane-place-zabaw-wynajem',
    getParentRoute: () => rootRouteImport,
  } as any)
const DmuchanceNaUrodzinyRoute = DmuchanceNaUrodzinyRouteImport.update({
  id: '/dmuchance-na-urodziny',
  path: '/dmuchance-na-urodziny',
  getParentRoute: () => rootRouteImport,
} as any)
const DmuchanceNaKomunieRoute = DmuchanceNaKomunieRouteImport.update({
  id: '/dmuchance-na-komunie',
  path: '/dmuchance-na-komunie',
  getParentRoute: () => rootRouteImport,
} as any)
const DmuchanceNaFestynyRoute = DmuchanceNaFestynyRouteImport.update({
  id: '/dmuchance-na-festyny',
  path: '/dmuchance-na-festyny',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RezerwacjaPublicTokenRoute = RezerwacjaPublicTokenRouteImport.update({
  id: '/rezerwacja/$publicToken',
  path: '/rezerwacja/$publicToken',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktySlugRoute = ProduktySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProduktyRoute,
} as any)
const KategorieSlugRoute = KategorieSlugRouteImport.update({
  id: '/kategorie/$slug',
  path: '/kategorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvailabilityRoute = AdminAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsIdRoute = AdminRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRequestsRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminBookingsIdRoute = AdminBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/dmuchance-na-festyny': typeof DmuchanceNaFestynyRoute
  '/dmuchance-na-komunie': typeof DmuchanceNaKomunieRoute
  '/dmuchance-na-urodziny': typeof DmuchanceNaUrodzinyRoute
  '/dmuchane-place-zabaw-wynajem': typeof DmuchanePlaceZabawWynajemRoute
  '/dmuchane-zjezdzalnie-wynajem': typeof DmuchaneZjezdzalnieWynajemRoute
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/maszyna-do-popcornu-wynajem': typeof MaszynaDoPopcornuWynajemRoute
  '/maszyna-do-waty-cukrowej-wynajem': typeof MaszynaDoWatyCukrowejWynajemRoute
  '/namiot-imprezowy-wynajem': typeof NamiotImprezowyWynajemRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/produkty': typeof ProduktyRouteWithChildren
  '/regulamin': typeof RegulaminRoute
  '/todos': typeof TodosRoute
  '/wynajem': typeof WynajemRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/kategorie/$slug': typeof KategorieSlugRoute
  '/produkty/$slug': typeof ProduktySlugRoute
  '/rezerwacja/$publicToken': typeof RezerwacjaPublicTokenRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/dmuchance-na-festyny': typeof DmuchanceNaFestynyRoute
  '/dmuchance-na-komunie': typeof DmuchanceNaKomunieRoute
  '/dmuchance-na-urodziny': typeof DmuchanceNaUrodzinyRoute
  '/dmuchane-place-zabaw-wynajem': typeof DmuchanePlaceZabawWynajemRoute
  '/dmuchane-zjezdzalnie-wynajem': typeof DmuchaneZjezdzalnieWynajemRoute
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/maszyna-do-popcornu-wynajem': typeof MaszynaDoPopcornuWynajemRoute
  '/maszyna-do-waty-cukrowej-wynajem': typeof MaszynaDoWatyCukrowejWynajemRoute
  '/namiot-imprezowy-wynajem': typeof NamiotImprezowyWynajemRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/produkty': typeof ProduktyRouteWithChildren
  '/regulamin': typeof RegulaminRoute
  '/todos': typeof TodosRoute
  '/wynajem': typeof WynajemRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/kategorie/$slug': typeof KategorieSlugRoute
  '/produkty/$slug': typeof ProduktySlugRoute
  '/rezerwacja/$publicToken': typeof RezerwacjaPublicTokenRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/dmuchance-na-festyny': typeof DmuchanceNaFestynyRoute
  '/dmuchance-na-komunie': typeof DmuchanceNaKomunieRoute
  '/dmuchance-na-urodziny': typeof DmuchanceNaUrodzinyRoute
  '/dmuchane-place-zabaw-wynajem': typeof DmuchanePlaceZabawWynajemRoute
  '/dmuchane-zjezdzalnie-wynajem': typeof DmuchaneZjezdzalnieWynajemRoute
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/maszyna-do-popcornu-wynajem': typeof MaszynaDoPopcornuWynajemRoute
  '/maszyna-do-waty-cukrowej-wynajem': typeof MaszynaDoWatyCukrowejWynajemRoute
  '/namiot-imprezowy-wynajem': typeof NamiotImprezowyWynajemRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/produkty': typeof ProduktyRouteWithChildren
  '/regulamin': typeof RegulaminRoute
  '/todos': typeof TodosRoute
  '/wynajem': typeof WynajemRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/kategorie/$slug': typeof KategorieSlugRoute
  '/produkty/$slug': typeof ProduktySlugRoute
  '/rezerwacja/$publicToken': typeof RezerwacjaPublicTokenRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cookies'
    | '/dashboard'
    | '/dmuchance-na-festyny'
    | '/dmuchance-na-komunie'
    | '/dmuchance-na-urodziny'
    | '/dmuchane-place-zabaw-wynajem'
    | '/dmuchane-zjezdzalnie-wynajem'
    | '/faq'
    | '/kontakt'
    | '/login'
    | '/maszyna-do-popcornu-wynajem'
    | '/maszyna-do-waty-cukrowej-wynajem'
    | '/namiot-imprezowy-wynajem'
    | '/polityka-prywatnosci'
    | '/produkty'
    | '/regulamin'
    | '/todos'
    | '/wynajem'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/requests'
    | '/admin/settings'
    | '/kategorie/$slug'
    | '/produkty/$slug'
    | '/rezerwacja/$publicToken'
    | '/admin/bookings/$id'
    | '/admin/products/$id'
    | '/admin/requests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cookies'
    | '/dashboard'
    | '/dmuchance-na-festyny'
    | '/dmuchance-na-komunie'
    | '/dmuchance-na-urodziny'
    | '/dmuchane-place-zabaw-wynajem'
    | '/dmuchane-zjezdzalnie-wynajem'
    | '/faq'
    | '/kontakt'
    | '/login'
    | '/maszyna-do-popcornu-wynajem'
    | '/maszyna-do-waty-cukrowej-wynajem'
    | '/namiot-imprezowy-wynajem'
    | '/polityka-prywatnosci'
    | '/produkty'
    | '/regulamin'
    | '/todos'
    | '/wynajem'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/requests'
    | '/admin/settings'
    | '/kategorie/$slug'
    | '/produkty/$slug'
    | '/rezerwacja/$publicToken'
    | '/admin/bookings/$id'
    | '/admin/products/$id'
    | '/admin/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cookies'
    | '/dashboard'
    | '/dmuchance-na-festyny'
    | '/dmuchance-na-komunie'
    | '/dmuchance-na-urodziny'
    | '/dmuchane-place-zabaw-wynajem'
    | '/dmuchane-zjezdzalnie-wynajem'
    | '/faq'
    | '/kontakt'
    | '/login'
    | '/maszyna-do-popcornu-wynajem'
    | '/maszyna-do-waty-cukrowej-wynajem'
    | '/namiot-imprezowy-wynajem'
    | '/polityka-prywatnosci'
    | '/produkty'
    | '/regulamin'
    | '/todos'
    | '/wynajem'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/requests'
    | '/admin/settings'
    | '/kategorie/$slug'
    | '/produkty/$slug'
    | '/rezerwacja/$publicToken'
    | '/admin/bookings/$id'
    | '/admin/products/$id'
    | '/admin/requests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  DmuchanceNaFestynyRoute: typeof DmuchanceNaFestynyRoute
  DmuchanceNaKomunieRoute: typeof DmuchanceNaKomunieRoute
  DmuchanceNaUrodzinyRoute: typeof DmuchanceNaUrodzinyRoute
  DmuchanePlaceZabawWynajemRoute: typeof DmuchanePlaceZabawWynajemRoute
  DmuchaneZjezdzalnieWynajemRoute: typeof DmuchaneZjezdzalnieWynajemRoute
  FaqRoute: typeof FaqRoute
  KontaktRoute: typeof KontaktRoute
  LoginRoute: typeof LoginRoute
  MaszynaDoPopcornuWynajemRoute: typeof MaszynaDoPopcornuWynajemRoute
  MaszynaDoWatyCukrowejWynajemRoute: typeof MaszynaDoWatyCukrowejWynajemRoute
  NamiotImprezowyWynajemRoute: typeof NamiotImprezowyWynajemRoute
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
  ProduktyRoute: typeof ProduktyRouteWithChildren
  RegulaminRoute: typeof RegulaminRoute
  TodosRoute: typeof TodosRoute
  WynajemRoute: typeof WynajemRoute
  KategorieSlugRoute: typeof KategorieSlugRoute
  RezerwacjaPublicTokenRoute: typeof RezerwacjaPublicTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wynajem': {
      id: '/wynajem'
      path: '/wynajem'
      fullPath: '/wynajem'
      preLoaderRoute: typeof WynajemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkty': {
      id: '/produkty'
      path: '/produkty'
      fullPath: '/produkty'
      preLoaderRoute: typeof ProduktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namiot-imprezowy-wynajem': {
      id: '/namiot-imprezowy-wynajem'
      path: '/namiot-imprezowy-wynajem'
      fullPath: '/namiot-imprezowy-wynajem'
      preLoaderRoute: typeof NamiotImprezowyWynajemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maszyna-do-waty-cukrowej-wynajem': {
      id: '/maszyna-do-waty-cukrowej-wynajem'
      path: '/maszyna-do-waty-cukrowej-wynajem'
      fullPath: '/maszyna-do-waty-cukrowej-wynajem'
      preLoaderRoute: typeof MaszynaDoWatyCukrowejWynajemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maszyna-do-popcornu-wynajem': {
      id: '/maszyna-do-popcornu-wynajem'
      path: '/maszyna-do-popcornu-wynajem'
      fullPath: '/maszyna-do-popcornu-wynajem'
      preLoaderRoute: typeof MaszynaDoPopcornuWynajemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmuchane-zjezdzalnie-wynajem': {
      id: '/dmuchane-zjezdzalnie-wynajem'
      path: '/dmuchane-zjezdzalnie-wynajem'
      fullPath: '/dmuchane-zjezdzalnie-wynajem'
      preLoaderRoute: typeof DmuchaneZjezdzalnieWynajemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmuchane-place-zabaw-wynajem': {
      id: '/dmuchane-place-zabaw-wynajem'
      path: '/dmuchane-place-zabaw-wynajem'
      fullPath: '/dmuchane-place-zabaw-wynajem'
      preLoaderRoute: typeof DmuchanePlaceZabawWynajemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmuchance-na-urodziny': {
      id: '/dmuchance-na-urodziny'
      path: '/dmuchance-na-urodziny'
      fullPath: '/dmuchance-na-urodziny'
      preLoaderRoute: typeof DmuchanceNaUrodzinyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmuchance-na-komunie': {
      id: '/dmuchance-na-komunie'
      path: '/dmuchance-na-komunie'
      fullPath: '/dmuchance-na-komunie'
      preLoaderRoute: typeof DmuchanceNaKomunieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmuchance-na-festyny': {
      id: '/dmuchance-na-festyny'
      path: '/dmuchance-na-festyny'
      fullPath: '/dmuchance-na-festyny'
      preLoaderRoute: typeof DmuchanceNaFestynyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rezerwacja/$publicToken': {
      id: '/rezerwacja/$publicToken'
      path: '/rezerwacja/$publicToken'
      fullPath: '/rezerwacja/$publicToken'
      preLoaderRoute: typeof RezerwacjaPublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkty/$slug': {
      id: '/produkty/$slug'
      path: '/$slug'
      fullPath: '/produkty/$slug'
      preLoaderRoute: typeof ProduktySlugRouteImport
      parentRoute: typeof ProduktyRoute
    }
    '/kategorie/$slug': {
      id: '/kategorie/$slug'
      path: '/kategorie/$slug'
      fullPath: '/kategorie/$slug'
      preLoaderRoute: typeof KategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/availability': {
      id: '/admin/availability'
      path: '/availability'
      fullPath: '/admin/availability'
      preLoaderRoute: typeof AdminAvailabilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests/$id': {
      id: '/admin/requests/$id'
      path: '/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AdminRequestsIdRouteImport
      parentRoute: typeof AdminRequestsRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/bookings/$id': {
      id: '/admin/bookings/$id'
      path: '/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AdminBookingsIdRouteImport
      parentRoute: typeof AdminBookingsRoute
    }
  }
}

interface AdminBookingsRouteChildren {
  AdminBookingsIdRoute: typeof AdminBookingsIdRoute
}

const AdminBookingsRouteChildren: AdminBookingsRouteChildren = {
  AdminBookingsIdRoute: AdminBookingsIdRoute,
}

const AdminBookingsRouteWithChildren = AdminBookingsRoute._addFileChildren(
  AdminBookingsRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsIdRoute: typeof AdminProductsIdRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsIdRoute: AdminProductsIdRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRequestsRouteChildren {
  AdminRequestsIdRoute: typeof AdminRequestsIdRoute
}

const AdminRequestsRouteChildren: AdminRequestsRouteChildren = {
  AdminRequestsIdRoute: AdminRequestsIdRoute,
}

const AdminRequestsRouteWithChildren = AdminRequestsRoute._addFileChildren(
  AdminRequestsRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminAvailabilityRoute: typeof AdminAvailabilityRoute
  AdminBookingsRoute: typeof AdminBookingsRouteWithChildren
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminRequestsRoute: typeof AdminRequestsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminAvailabilityRoute: AdminAvailabilityRoute,
  AdminBookingsRoute: AdminBookingsRouteWithChildren,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminRequestsRoute: AdminRequestsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProduktyRouteChildren {
  ProduktySlugRoute: typeof ProduktySlugRoute
}

const ProduktyRouteChildren: ProduktyRouteChildren = {
  ProduktySlugRoute: ProduktySlugRoute,
}

const ProduktyRouteWithChildren = ProduktyRoute._addFileChildren(
  ProduktyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  DmuchanceNaFestynyRoute: DmuchanceNaFestynyRoute,
  DmuchanceNaKomunieRoute: DmuchanceNaKomunieRoute,
  DmuchanceNaUrodzinyRoute: DmuchanceNaUrodzinyRoute,
  DmuchanePlaceZabawWynajemRoute: DmuchanePlaceZabawWynajemRoute,
  DmuchaneZjezdzalnieWynajemRoute: DmuchaneZjezdzalnieWynajemRoute,
  FaqRoute: FaqRoute,
  KontaktRoute: KontaktRoute,
  LoginRoute: LoginRoute,
  MaszynaDoPopcornuWynajemRoute: MaszynaDoPopcornuWynajemRoute,
  MaszynaDoWatyCukrowejWynajemRoute: MaszynaDoWatyCukrowejWynajemRoute,
  NamiotImprezowyWynajemRoute: NamiotImprezowyWynajemRoute,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
  ProduktyRoute: ProduktyRouteWithChildren,
  RegulaminRoute: RegulaminRoute,
  TodosRoute: TodosRoute,
  WynajemRoute: WynajemRoute,
  KategorieSlugRoute: KategorieSlugRoute,
  RezerwacjaPublicTokenRoute: RezerwacjaPublicTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
